In [1]:
import pandas as pd
print(pd.__version__)

ventas=pd.read_csv("C:/Users/Usuario/Documents/data-science/01-pyton-intro/ventas.csv")
ventas.head(n=10)

ventas["importe"]=ventas["unidades"]*ventas["precio_unitario"]
ventas

3.0.5

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento,importe
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00,650
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00,4480
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00,280
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00,12000
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10,260
...,...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00,180
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05,15600
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05,640
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00,1920
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00,360

In [2]:
ventas.groupby("region")["importe"].sum()

region
Centro    705695
Este      549745
Norte     862360
Oeste     626295
Sur       699920
Name: importe, dtype: int64

In [3]:
ventas[ventas["region"]=="Sur"]["importe"].sum()

np.int64(699920)

In [7]:
ventas.groupby("region")["importe"].agg(["sum","mean","count"])

           sum         mean  count
region
Centro  705695  2594.466912    272
Este    549745  3054.138889    180
Norte   862360  2827.409836    305
Oeste   626295  3085.197044    203
Sur     699920  2916.333333    240

In [9]:
ventas.groupby(["region","categoria"])["importe"].agg(["sum","mean","count"])

                      sum         mean  count
region categoria
Centro Accesorios   56895   605.265957     94
       Mobiliario  201520  2651.578947     76
       Tecnologia  447280  4385.098039    102
Este   Accesorios   44585   675.530303     66
       Mobiliario  136520  2730.400000     50
       Tecnologia  368640  5760.000000     64
Norte  Accesorios   78630   639.268293    123
       Mobiliario  200130  2668.400000     75
       Tecnologia  583600  5454.205607    107
Oeste  Accesorios   40205   628.203125     64
       Mobiliario  156170  2692.586207     58
       Tecnologia  429920  5307.654321     81
Sur    Accesorios   57800   642.222222     90
       Mobiliario  155320  2724.912281     57
       Tecnologia  486800  5234.408602     93

In [11]:
ventas.groupby(["region","categoria"])["importe"].agg(
    importe_total="sum",
    importe_promedio="mean",
    total_registrados="count"
)

                   importe_total  importe_promedio  total_registrados
region categoria
Centro Accesorios          56895        605.265957                 94
       Mobiliario         201520       2651.578947                 76
       Tecnologia         447280       4385.098039                102
Este   Accesorios          44585        675.530303                 66
       Mobiliario         136520       2730.400000                 50
       Tecnologia         368640       5760.000000                 64
Norte  Accesorios          78630        639.268293                123
       Mobiliario         200130       2668.400000                 75
       Tecnologia         583600       5454.205607                107
Oeste  Accesorios          40205        628.203125                 64
       Mobiliario         156170       2692.586207                 58
       Tecnologia         429920       5307.654321                 81
Sur    Accesorios          57800        642.222222                 90
       Mobiliario         155320       2724.912281                 57
       Tecnologia         486800       5234.408602                 93

In [13]:
ventas.groupby("region").agg({
    "importe": ["sum","mean","max"],
    "unidades":["sum"],
    "producto": ["nunique"]
})

       importe                     unidades producto
           sum         mean    max      sum  nunique
region
Centro  705695  2594.466912  15600     1933        8
Este    549745  3054.138889  16800     1384        8
Norte   862360  2827.409836  16800     2166        8
Oeste   626295  3085.197044  15600     1469        8
Sur     699920  2916.333333  16800     1779        8